# fly.toml app configuration file generated for tic-tac-toe-58125 on 2024-01-24T15:08:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tic-tac-toe-nextjs"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
