# fly.toml app configuration file generated for tic-tac-toe-dev on 2024-01-25T13:37:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
