name: Lint and Test Composite Action
description: Runs Lint, Test and uploads coverage artifact to be used in separate sonarcloud job
runs:
  using: 'composite'
  steps:
    - name: Linting
      run: pnpm run lint && pnpm run format:fix
      shell: bash

    - name: Test
      run: pnpm run test:coverage
      shell: bash

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage
