name: Deployment Composite Action
description: Deploys app to DEV or PROD depending on the branch
runs:
  using: 'composite'
  steps:
    - name: Set up flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to DEV
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: flyctl deploy --app tic-tac-toe-dev --remote-only --ha=false
      shell: bash

    - name: Deploy to PROD on Fly.io
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: flyctl deploy --app tic-tac-toe-prod --remote-only --ha=false
      shell: bash

    - name: Deploy to PROD on Vercel
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        pnpm i --global vercel@latest
        vercel build --prod --token=${{ secrets.TIC_TAC_TOE_VERCEL_TOKEN }}
        vercel --prod --token ${{ secrets.TIC_TAC_TOE_VERCEL_TOKEN }}
      shell: bash
