export const FINISH_ROUND = 'FINISH_ROUND';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_CURRENT_PLAYER = 'UPDATE_CURRENT_PLAYER';
export const UPDATE_ROUND_STATUS = 'UPDATE_ROUND_STATUS';
