name: Build and Deploy

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]
  push:
    branches:
      - development
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.14.2
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Linting
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: pnpm run lint && pnpm run format:fix

    - name: Test
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: pnpm run test:coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage

    - name: Build application
      run: pnpm run build

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all commits and history will be fetched during the checkout process.

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any (automatically created on behalf of github)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - sonarcloud

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to DEV
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: flyctl deploy --app tic-tac-toe-dev --remote-only --ha=false

    - name: Deploy to PROD
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: flyctl deploy --app tic-tac-toe-prod --remote-only --ha=false
