name: Build and Deploy

on:
  push:
    branches:
      - development
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install pnpm & install dependencies
      run: npm install -g pnpm && pnpm i --frozen-lockfile

    - name: Linting
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: pnpm run lint && pnpm run format:fix

    - name: Test
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: pnpm run test

    - name: Build application
      run: pnpm run build

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all commits and history will be fetched during the checkout process.
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any (automatically created on behalf of github)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build
      - sonarcloud

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to DEV
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      run: flyctl deploy --app tic-tac-toe-dev --remote-only --ha=false

    - name: Deploy to PROD
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: flyctl deploy --app tic-tac-toe-prod --remote-only --ha=false
