name: PROD

on:
  push:
    branches:
      - master

jobs:
  common:
    strategy:
      matrix:
        branch: [master]
        lint: [false]
        appName: ['tic-tac-toe-prod']

    runs-on: ubuntu-latest
    steps:
      - name: Run Common Build
        uses: ./.github/workflows/common.yaml
