name: Build and Deploy

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]
  push:
    branches:
      - development
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TIC_TAC_TOE_VERCEL_TOKEN: ${{ secrets.TIC_TAC_TOE_VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.14.2
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Lint and Test Composite Action
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'
      uses: ./.github/actions/lint_and_test

    - name: Build application
      run: pnpm run build

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all commits and history will be fetched during the checkout process.
      - name: SonarCloud Composite Action
        uses: ./.github/actions/sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - sonarcloud
    steps:
      - name: Deployment Composite Action (DEV or PROD)
        uses: ./.github/actions/deploy
