name: SonarCloud Composite Action
description: Sonarcloud scan
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  sonar_token:
    description: 'Sonar Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download coverage artifact
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
        path: coverage

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        github_token: ${{ inputs.github_token }}
        sonar_token: ${{ inputs.sonar_token }}
