name: SonarCloud Composite Action
description: Sonarcloud scan

runs:
  using: 'composite'
  steps:
    - name: Download coverage artifact
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
        path: coverage

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
